version: "3"

services:
  app:
    image: ngoduykhanh/powerdns-admin:latest
    container_name: powerdns_admin
    ports:
      - "9164:80"
    logging:
      driver: json-file
      options:
        max-size: 50m
    restart: always
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://pdnsadminuser:p4ssw0rd@10.49.12.64/powerdnsadmin
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
      - OFFLINE_MODE=False # True for offline, False for external resources
